=== atlaskerr/registry-spec/schema/namespace/namespace.schema.json
{
   "$id": "https://openpackages.io/schema/namespace",
   "$schema": "http://json-schema.org/draft-07/schema#",
   "properties": {
      "labels": {
         "properties": {
            "labels": {
               "properties": {
                  "consumer": {
                     "patternProperties": {
                        ".{1,}": {
                           "type": "string"
                        }
                     },
                     "type": "object"
                  },
                  "provider": {
                     "patternProperties": {
                        ".{1,}": {
                           "type": "string"
                        }
                     },
                     "type": "object"
                  }
               },
               "type": "object"
            }
         },
         "type": "object"
      },
      "name": {
         "type": "string"
      },
      "quotas": {
         "properties": {
            "projects": {
               "properties": {
                  "limit": {
                     "maximum": 18446744073709551616,
                     "minimum": 0,
                     "type": "integer"
                  },
                  "used": {
                     "maximum": 18446744073709551616,
                     "minimum": 0,
                     "type": "integer"
                  }
               },
               "type": "object"
            },
            "repositories": {
               "properties": {
                  "limit": {
                     "maximum": 18446744073709551616,
                     "minimum": 0,
                     "type": "integer"
                  },
                  "used": {
                     "maximum": 18446744073709551616,
                     "minimum": 0,
                     "type": "integer"
                  }
               },
               "type": "object"
            },
            "storage": {
               "properties": {
                  "limit": {
                     "maximum": 18446744073709551616,
                     "minimum": 0,
                     "type": "integer"
                  },
                  "used": {
                     "maximum": 18446744073709551616,
                     "minimum": 0,
                     "type": "integer"
                  }
               },
               "type": "object"
            }
         },
         "type": "object"
      },
      "status": {
         "enum": [
            "active",
            "terminating"
         ],
         "type": "string"
      }
   },
   "type": "object"
}

=== atlaskerr/registry-spec/schema/namespace/namespace.golden.json
{
   "labels": {
      "consumer": {
         "costCenter": "cs-foo",
         "manager": "Tom Ripen",
         "team": "team-foo"
      },
      "provider": {
         "awsAccount": "aws-account-foo",
         "pricingPlan": "PREMIUM",
         "region": "us-east-1"
      }
   },
   "name": "namespace-foo",
   "quotas": {
      "projects": {
         "limit": 75,
         "used": 14
      },
      "repositories": {
         "limit": 100,
         "used": 23
      },
      "storage": {
         "limit": 548298572358,
         "used": 580324752
      }
   },
   "status": "active"
}
