=== atlaskerr/registry-spec/schema/repository/repository.single.schema.json
{
   "$id": "https://openpackages.io/schema/repo",
   "$schema": "http://json-schema.org/draft-07/schema#",
   "additionalProperties": false,
   "properties": {
      "labels": {
         "patternProperties": {
            ".{1,}": {
               "type": "string"
            }
         },
         "type": "object"
      },
      "name": {
         "type": "string"
      },
      "namespace": {
         "type": "string"
      },
      "package": {
         "additionalProperties": false,
         "properties": {
            "documentation": {
               "type": "string"
            },
            "icon": {
               "type": "string"
            },
            "type": {
               "type": "string"
            }
         },
         "type": "object"
      },
      "project": {
         "type": "string"
      },
      "size": {
         "maximum": 18446744073709551616,
         "minimum": 0,
         "type": "integer"
      }
   },
   "type": "object"
}

=== atlaskerr/registry-spec/schema/repository/repository.single.example.json
{
   "labels": {
      "costCenter": "cs-foo",
      "maintainer": "Billy Seiken",
      "team": "team-example"
   },
   "name": "repository-example-foo",
   "namespace": "namespace-example-foo",
   "package": {
      "documentation": "https://github.com/opencontainers/image-spec",
      "icon": "https://opencontainers/static/icon-small.png",
      "type": "OCI Image"
   },
   "project": "project-example-foo",
   "size": 34252334
}
